language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

# Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# Use APT Addon to install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# Start Xvfb so you can run headless Chrome
before_install:
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --prod
  - ng test --code-coverage --watch=false

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/Icov.info
