language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

notifications:
  email: false

before_script:
  - npm install -g --silent @angular/cli

script:
  - ng build --prod
  - ng test --code-coverage --watch=false

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/Icov.info
