name: build

on:
  push:
    branches: [ develop, master, feature/angular-11 ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # - run: npm ci
    # - run: npm run build --if-present
    - run: ng build --prod
    - run: ng test --code-coverage --watch=false
    - uses: codecov/codecov-action@v1
